import '../scss/utils/normalize.css'
import '../scss/utils/null.css'
import '../scss/fonts.scss'
import '../scss/utils/vars.scss'
import '../scss/style.scss'

import '../scss/parts/button.scss'
import '../scss/parts/divider.scss'
import '../scss/parts/logo.scss'
import '../scss/parts/menu.scss'
import '../scss/parts/button-box.scss'
import '../scss/parts/long-line.scss'
import '../scss/parts/page-divider.scss'
import '../scss/parts/brand-item.scss'
import '../scss/parts/technics-item.scss'
import '../scss/parts/modal.scss'

import '../scss/parts/header.scss'
import '../scss/parts/aside.scss'
import '../scss/parts/services.scss'
import '../scss/parts/about.scss'
import '../scss/parts/brands.scss'
import '../scss/parts/technics.scss'
import '../scss/parts/table.scss'
import '../scss/parts/prices.scss'
import '../scss/parts/footer.scss'
