import '../scss/normalize.css'
import '../scss/null.css'
import '../scss/fonts.scss'
import '../scss/vars.scss'
import '../scss/style.scss'

import '../blocks/button/button.scss'
import '../blocks/divider/divider.scss'
import '../blocks/logo/logo.scss'
import '../blocks/menu/menu.scss'
import '../blocks/button-box/button-box.scss'
import '../blocks/long-line/long-line.scss'
import '../blocks/page-divider/page-divider.scss'
import '../blocks/brand-item/brand-item.scss'
import '../blocks/technics-item/technics-item.scss'
import '../blocks/modal/modal.scss'

import '../blocks/header/header.scss'
import '../blocks/aside/aside.scss'
import '../blocks/services/services.scss'
import '../blocks/about/about.scss'
import '../blocks/brands/brands.scss'
import '../blocks/technics/technics.scss'
import '../blocks/table/table.scss'
import '../blocks/prices/prices.scss'
import '../blocks/footer/footer.scss'
